version: '3.9'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    hostname: web
    container_name: web
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 80:5000
    env_file:
      - ./.env
  db:
    image: postgres
    hostname: db
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin

volumes:
  postgres_data:
